name:                GoM
version:             2019.5.16
github:              "magicloud/GoM"
license:             BSD3
author:              "Magicloud"
maintainer:          "magiclouds@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            system

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/magicloud/GoM#readme>

dependencies:
- base >= 4.7 && < 5
- unix
- directory
- notifySend
- filepath
- bytestring

library:
  source-dirs: src

executables:
  GoM:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    dependencies:
    - GoM
